#! /bin/sh

RED="\033[0;31m"
RESET="\033[0m"

echo "Running test"
npm run test 
if [ "$?" -ne 0 ]; then
  echo "${RED} ***** FAILING TESTS ***** ${RESET}" 
  exit 1
fi

echo "Running coverage"
npm run coverage

echo "Checking coverage threshold"
nyc check-coverage 
if [ "$?" -ne 0 ]; then
  echo "${RED} ***** COVERAGE BELOW 90% ***** ${RESET}"
  exit 1
fi

echo "Running linter"
npm run lint
if [ "$?" -ne 0 ]; then
  echo "${RED} ***** LINTING ERRORS ***** ${RESET}"
  exit 1
fi

exit 0